"""Safe repository scanning, glob search, and static Python dependency inspection."""

from __future__ import annotations

import ast
import subprocess
from collections.abc import Sequence
from dataclasses import dataclass
from pathlib import Path
from typing import Protocol

from services.process_runner import repository_subprocess_environment
from tools.file_tools import PathLike, WorkspacePathError, list_files, resolve_workspace_path

DEFAULT_IGNORED_DIRECTORIES = frozenset(
    {
        ".git",
        ".mypy_cache",
        ".pytest_cache",
        ".ruff_cache",
        ".venv",
        "__pycache__",
        "node_modules",
    }
)
# Build output, dropped only when the checkout cannot answer for itself. Deliberately NOT in
# the set above: those seven are never source in any repository, and these six frequently
# are. A repository that tracks its `dist/` is telling us that directory is source, and its
# index is a better authority than any list this module can hold -- so when Git answers, Git
# decides, and this is the fallback for a root with no Git to ask.
GENERATED_OUTPUT_DIRECTORIES = frozenset({".next", ".nuxt", "build", "coverage", "dist", "out"})
# A scan is on the attempt's critical path and asks Git two bounded questions. Neither is
# allowed to hang the walk; an unanswered question falls back to the static sets.
_GIT_QUERY_TIMEOUT_SECONDS = 10.0


@dataclass(frozen=True, slots=True)
class DirectoryScan:
    """An inventory of the regular files and directories below a workspace path."""

    root: Path
    files: tuple[Path, ...]
    directories: tuple[Path, ...]
    total_size_bytes: int


class RepositoryTool(Protocol):
    """Protocol for repository inspection constrained to one configured workspace."""

    def scan_directory(self, relative_directory: PathLike = ".") -> DirectoryScan:
        """Return a directory inventory."""

    def find_files(
        self, patterns: tuple[str, ...], relative_directory: PathLike = "."
    ) -> list[Path]:
        """Find files matching glob patterns."""

    def inspect_python_dependencies(
        self, relative_directory: PathLike = "."
    ) -> dict[Path, tuple[str, ...]]:
        """Inspect imports without executing repository code."""


class WorkspaceRepositoryTools:
    """A reusable repository-tool implementation bound to one workspace root."""

    def __init__(self, workspace_root: PathLike) -> None:
        """Store the root used for all later scan and inspection requests."""
        self.workspace_root = resolve_workspace_path(workspace_root, ".")

    def scan_directory(self, relative_directory: PathLike = ".") -> DirectoryScan:
        """Scan a directory in the configured workspace."""
        return scan_directory(self.workspace_root, relative_directory)

    def find_files(
        self, patterns: tuple[str, ...], relative_directory: PathLike = "."
    ) -> list[Path]:
        """Find matching files in the configured workspace."""
        return find_files(self.workspace_root, patterns, relative_directory)

    def inspect_python_dependencies(
        self, relative_directory: PathLike = "."
    ) -> dict[Path, tuple[str, ...]]:
        """Inspect Python imports in the configured workspace."""
        return inspect_python_dependencies(self.workspace_root, relative_directory)


def scan_directory(
    workspace_root: PathLike,
    relative_directory: PathLike = ".",
    *,
    ignored_directories: frozenset[str] = DEFAULT_IGNORED_DIRECTORIES,
) -> DirectoryScan:
    """Inventory a directory without following links outside the workspace root.

    The inventory is the repository, not its build output. This walks the working tree, and
    a working tree contains whatever the last command wrote into it -- including, in this
    platform, the output of its own baseline build. AB-Feature-218 spent eight of the
    engineer's sixty context slots on `dist/**` files that `git ls-files dist` does not
    return and `.gitignore` names, generated by the platform's own `npm run build` minutes
    earlier and fed straight back to the model, while the source file the instruction told
    it to reuse never made the snapshot at all.

    So the checkout's own ignore rules decide, when there is a checkout to ask: Git is the
    only authority that knows which of these directories this repository considers
    generated. Tracked paths win over the ignore rules, because a repository that commits a
    file has settled the question whatever a parent directory's pattern says.
    ``GENERATED_OUTPUT_DIRECTORIES`` is the fallback for a root with no Git, and the walk
    fails closed throughout: a question Git cannot answer leaves the static sets in charge
    rather than admitting everything.
    """
    root = resolve_workspace_path(workspace_root, ".")
    directory = resolve_workspace_path(root, relative_directory)
    if not directory.is_dir():
        msg = f"path is not a directory: {relative_directory}"
        raise NotADirectoryError(msg)

    files: list[Path] = []
    directories: list[Path] = []
    for candidate in directory.rglob("*"):
        relative_candidate = candidate.relative_to(root)
        if _contains_ignored_component(relative_candidate, ignored_directories):
            continue
        try:
            resolved_candidate = resolve_workspace_path(root, candidate)
        except WorkspacePathError:
            continue
        if resolved_candidate.is_dir():
            directories.append(resolved_candidate.relative_to(root))
        elif resolved_candidate.is_file():
            files.append(resolved_candidate.relative_to(root))

    generated = _generated_paths(root, files)
    kept = [
        path
        for path in sorted(set(files), key=lambda item: item.as_posix())
        if path.as_posix() not in generated
    ]
    total_size_bytes = 0
    for path in kept:
        try:
            total_size_bytes += (root / path).stat().st_size
        except OSError:
            continue

    return DirectoryScan(
        root=directory.relative_to(root),
        files=tuple(kept),
        directories=tuple(
            path
            for path in sorted(set(directories), key=lambda item: item.as_posix())
            if path.as_posix() not in generated
        ),
        total_size_bytes=total_size_bytes,
    )


def _generated_paths(root: Path, candidates: Sequence[Path]) -> frozenset[str]:
    """Return the candidates this checkout treats as generated, by its own rules.

    Two bounded questions, in this order because the second only matters where the first
    says nothing: which paths are tracked, and which of the rest the ignore rules exclude.
    A tracked path is never generated here however it is spelled in `.gitignore` -- that is
    the case `git check-ignore` alone gets wrong, and a repository that vendors its build
    output into the index would otherwise lose it from every snapshot.

    Fails closed. A root with no Git, a Git that will not run, a timeout or an unexpected
    exit falls back to ``GENERATED_OUTPUT_DIRECTORIES`` over the same candidates, which is
    the same question answered worse rather than not answered at all.
    """
    if not (root / ".git").exists():
        return _statically_generated(candidates)
    if not candidates:
        return frozenset()
    tracked = _git_lines(root, ("ls-files", "-z"))
    if tracked is None:
        return _statically_generated(candidates)
    payload = "\0".join(path.as_posix() for path in candidates)
    ignored = _git_check_ignore(root, payload)
    if ignored is None:
        return _statically_generated(candidates)
    return frozenset(ignored - tracked)


def _statically_generated(candidates: Sequence[Path]) -> frozenset[str]:
    """The fallback answer: build output recognised by directory name alone."""
    return frozenset(
        path.as_posix()
        for path in candidates
        if _contains_ignored_component(path, GENERATED_OUTPUT_DIRECTORIES)
    )


def _git_lines(root: Path, arguments: tuple[str, ...]) -> set[str] | None:
    """Run a NUL-separated Git query, or ``None`` if the checkout would not answer."""
    try:
        result = subprocess.run(
            ("git", *arguments),
            cwd=root,
            check=False,
            capture_output=True,
            text=True,
            timeout=_GIT_QUERY_TIMEOUT_SECONDS,
            env=repository_subprocess_environment(),
        )
    except (OSError, subprocess.TimeoutExpired, ValueError):
        return None
    if result.returncode != 0:
        return None
    return {item for item in result.stdout.split("\0") if item}


def _git_check_ignore(root: Path, payload: str) -> set[str] | None:
    """Ask the checkout which of these paths its ignore rules exclude.

    Exit 1 means "none of them", which is an answer and not a failure -- the one place this
    differs from every other Git query in the platform.
    """
    try:
        result = subprocess.run(
            ("git", "check-ignore", "-z", "--stdin"),
            cwd=root,
            input=payload,
            check=False,
            capture_output=True,
            text=True,
            timeout=_GIT_QUERY_TIMEOUT_SECONDS,
            env=repository_subprocess_environment(),
        )
    except (OSError, subprocess.TimeoutExpired, ValueError):
        return None
    if result.returncode not in (0, 1):
        return None
    return {item for item in result.stdout.split("\0") if item}


def find_files(
    workspace_root: PathLike,
    patterns: tuple[str, ...],
    relative_directory: PathLike = ".",
    *,
    ignored_directories: frozenset[str] = DEFAULT_IGNORED_DIRECTORIES,
) -> list[Path]:
    """Return distinct workspace-relative files matching one or more safe glob patterns."""
    if not patterns:
        msg = "at least one glob pattern is required"
        raise ValueError(msg)

    matches: set[Path] = set()
    for pattern in patterns:
        for file_path in list_files(workspace_root, relative_directory, pattern=pattern):
            if not _contains_ignored_directory(file_path, ignored_directories):
                matches.add(file_path)
    return sorted(matches, key=lambda path: path.as_posix())


def inspect_python_dependencies(
    workspace_root: PathLike, relative_directory: PathLike = "."
) -> dict[Path, tuple[str, ...]]:
    """Parse Python imports into a deterministic dependency map without executing code."""
    dependencies: dict[Path, tuple[str, ...]] = {}
    for file_path in find_files(workspace_root, ("**/*.py",), relative_directory):
        source = (resolve_workspace_path(workspace_root, file_path)).read_text(encoding="utf-8")
        parsed = ast.parse(source, filename=file_path.as_posix())
        imported_modules: set[str] = set()
        for node in ast.walk(parsed):
            if isinstance(node, ast.Import):
                imported_modules.update(alias.name for alias in node.names)
            elif isinstance(node, ast.ImportFrom):
                relative_prefix = "." * node.level
                if node.module is not None:
                    imported_modules.add(f"{relative_prefix}{node.module}")
                else:
                    imported_modules.update(
                        f"{relative_prefix}{alias.name}" for alias in node.names
                    )
        dependencies[file_path] = tuple(sorted(imported_modules))
    return dependencies


def inspect_dependencies(
    workspace_root: PathLike, relative_directory: PathLike = "."
) -> dict[Path, tuple[str, ...]]:
    """Provide a concise alias for Python dependency inspection."""
    return inspect_python_dependencies(workspace_root, relative_directory)


def _contains_ignored_directory(path: Path, ignored_directories: frozenset[str]) -> bool:
    """Return whether any directory component of a path is intentionally excluded."""
    return any(part in ignored_directories for part in path.parts[:-1])


def _contains_ignored_component(path: Path, ignored_directories: frozenset[str]) -> bool:
    """Return whether a scanned file or directory is inside an excluded component."""
    return any(part in ignored_directories for part in path.parts)
