"""Feature-level planning that creates one immutable contract for many repositories."""

from __future__ import annotations

import json
from collections.abc import Sequence
from datetime import UTC, datetime
from typing import Any, Protocol

from pydantic import ValidationError

from adapters.llm_adapter import LLMClient
from agents.shared.contract_sections import contract_section_names
from agents.shared.contracts import (
    ARTIFACT_FILENAMES,
    FEATURE_ARTIFACT_FILENAMES,
    AgentArtifactError,
    create_artifact,
    execution_metadata,
    parse_model_json,
    safe_error_diagnostics,
)
from agents.shared.design_snapshot import design_node_names, design_request_context
from agents.shared.task_graph import ordered_task_ids
from artifacts.schemas import (
    ArchitectureArtifact,
    DesignSnapshotArtifact,
    IntegrationContractArtifact,
    RepositoryExecutionPlanArtifact,
    RepositoryReconnaissanceArtifact,
    TechnicalPRDArtifact,
)
from prompts.prompt_loader import PromptLoader
from state.enums import DeploymentStrategy, MergeStrategy, WorkstreamRole
from state.feature_models import RepositorySpec
from tools.contract_tools import (
    ContractCodeGenerator,
    MockContractCodeGenerator,
    OpenAPIContractCodeGenerator,
)

# A repository in one of these roles publishes something its siblings build against, so
# they genuinely cannot start until it lands. Every other role coordinates purely through
# the already-approved integration contract and therefore runs in parallel.
_BUILD_ARTIFACT_ROLES = frozenset({WorkstreamRole.SHARED.value})


def _safe_planner_rejection(error: AgentArtifactError | ValidationError) -> str:
    """Return a useful platform-owned reason without retaining rejected model values."""
    if isinstance(error, ValidationError):
        diagnostics = safe_error_diagnostics(error)
        return "; ".join(diagnostics) or "planner response failed schema validation"

    # AgentArtifactError messages are generated by this module, but some deliberately
    # interpolate rejected identifiers so the repair model can correct them.  Persist only
    # the matching platform-owned category; the detailed message remains ephemeral.
    message = str(error)
    categories = (
        ("dependency cycle", "repository execution plan contains a dependency cycle"),
        ("unknown technical requirements", "workstream assigns unknown technical requirements"),
        ("unknown acceptance", "workstream references unknown acceptance criteria"),
        ("marks unknown requirements", "workstream marks unknown requirements out of scope"),
        (
            "assign every technical requirement",
            "required workstreams do not cover every requirement",
        ),
        (
            "submitted repositories",
            "repository execution plan does not match submitted repositories",
        ),
        ("valid JSON", "planner response is not valid JSON"),
        ("JSON object", "planner response has an invalid object shape"),
        ("contain exactly", "planner response has an invalid top-level shape"),
        ("envelope fields", "planner response attempted to replace artifact envelope fields"),
    )
    for marker, category in categories:
        if marker in message:
            return category
    return "planner response failed deterministic artifact validation"


class FeaturePlanner(Protocol):
    """Produce one architecture, contract, and repository assignment plan."""

    async def plan(
        self,
        *,
        feature_id: str,
        technical_prd: TechnicalPRDArtifact,
        repositories: list[RepositorySpec],
        reconnaissance: Sequence[RepositoryReconnaissanceArtifact] = (),
        design_snapshot: DesignSnapshotArtifact | None = None,
    ) -> tuple[ArchitectureArtifact, IntegrationContractArtifact, RepositoryExecutionPlanArtifact]:
        """Return the artifact set that gates all child workstreams.

        ``reconnaissance`` carries what each checkout actually contains. It defaults to empty
        so a planner can still run without it, but a live plan built without it is the blind
        plan this parameter exists to end.

        ``design_snapshot`` carries the frames the author attached. It defaults to `None`
        because most features attach none, and a plan for one of those is byte-identical to
        what it always was. Where there is one, this is the role that decides which repository
        each frame belongs to -- which is why it sees the whole design rather than a scoped
        selection of it.
        """


class FeaturePlannerAgent:
    """Use the technical-planning model once for all repository workstreams."""

    def __init__(
        self,
        *,
        prompt_loader: PromptLoader,
        llm_client: LLMClient,
        contract_generator: ContractCodeGenerator | None = None,
        # Off by default, and deliberately temporary in the same sense `bounded_review_scope`
        # is: with it off the prompt renders byte-identically to before this existed, and every
        # plan is built exactly as it is built today. See `configs/settings.py` for why.
        plan_task_dependencies: bool = False,
    ) -> None:
        """Inject the same bounded model boundary used by the existing technical planner."""
        self._prompt_loader = prompt_loader
        self._llm_client = llm_client
        self._contract_generator = contract_generator or OpenAPIContractCodeGenerator()
        self._plan_task_dependencies = plan_task_dependencies

    async def plan(
        self,
        *,
        feature_id: str,
        technical_prd: TechnicalPRDArtifact,
        repositories: list[RepositorySpec],
        reconnaissance: Sequence[RepositoryReconnaissanceArtifact] = (),
        design_snapshot: DesignSnapshotArtifact | None = None,
    ) -> tuple[ArchitectureArtifact, IntegrationContractArtifact, RepositoryExecutionPlanArtifact]:
        """Generate a single approved contract before a child is allowed to start."""
        design = design_request_context(design_snapshot)
        instructions = self._prompt_loader.render(
            "planner/feature_v1.jinja2",
            feature_id=feature_id,
            technical_prd=technical_prd.model_dump_json(indent=2),
            repositories=[item.model_dump(mode="json") for item in repositories],
            has_reconnaissance=bool(reconnaissance),
            reconnaissance=json.dumps(
                [item.model_dump(mode="json") for item in reconnaissance],
                indent=2,
                sort_keys=True,
            ),
            # Empty string rather than an empty block for the feature that cited nothing: the
            # template renders nothing at all for it, so its prompt is unchanged byte for byte.
            design_snapshot=(
                "" if design is None else json.dumps(design, indent=2, sort_keys=True)
            ),
            plan_task_dependencies=self._plan_task_dependencies,
        )
        response = await self._llm_client.respond(
            instructions=instructions,
            input_text=technical_prd.model_dump_json(indent=2),
        )
        metadata = {
            "source_artifact_ids": [
                technical_prd.artifact_id,
                *[item.artifact_id for item in reconnaissance],
            ],
            "model": response.model,
            "response_id": response.response_id,
            "prompt_template": "planner/feature_v1.jinja2",
            # Recorded so a plan can be told apart from one made before its checkouts were
            # read. Every failure traced to an assumed convention was produced by the second
            # kind, and the artifacts did not distinguish them.
            "reconnaissance_artifact_ids": [item.artifact_id for item in reconnaissance],
            "planned_from_checkout_evidence": bool(reconnaissance),
            **execution_metadata(
                agent_type="Technical planner",
                provider=response.provider,
                model=response.model,
                reasoning_effort=response.reasoning_effort,
                model_role=response.model_role,
                model_variable=response.model_variable,
                routing_reason=response.routing_reason,
            ),
        }
        try:
            payload = parse_model_json(
                response.output_text,
                expected_keys=("architecture", "integration_contract", "repository_execution_plan"),
            )
            return await self._validated_artifacts(
                feature_id=feature_id,
                technical_prd=technical_prd,
                repositories=repositories,
                payload=payload,
                metadata=metadata,
                design_snapshot=design_snapshot,
            )
        except (AgentArtifactError, ValidationError) as error:
            # All schema and dependency-graph validation sits inside this one bounded
            # repair path.  A model placing a consumer before its dependency is an
            # ordinary recoverable planning defect, never an HTTP 500.
            repair_response = await self._llm_client.respond(
                instructions=(
                    f"{instructions}\n\n"
                    "Your previous response was rejected by deterministic validation. Here is "
                    "your previous response:\n"
                    f"{response.output_text}\n\n"
                    f"Here is exactly what was wrong with it:\n{error}\n\n"
                    # A repair that reworks the whole plan trades the reported defect for new
                    # ones: an attempt rejected for two field errors came back with sixteen,
                    # having filled unrelated required strings with "". Anchoring the model to
                    # its own previous response keeps the correction to what actually failed.
                    "Return the complete planning response again with only the fields named "
                    "above changed. Every other field must be byte-identical to your previous "
                    "response. Do not restructure the plan, rename anything, or 'improve' a "
                    "field the errors did not mention, and do not introduce empty strings. "
                    "Keep the architecture and integration contract compatible unless the "
                    "scope correction requires a corresponding contract change. A technical "
                    "requirement may be assigned to multiple repositories only when each has "
                    "a different explicit responsibility. Exactly one repository implements "
                    "a shared API contract; dependent repositories consume, validate, or "
                    "document it. execution_order and parallel_groups must list every "
                    "dependency before the workstream that depends on it."
                ),
                input_text=technical_prd.model_dump_json(indent=2),
            )
            repair_metadata = {
                **metadata,
                "model": repair_response.model,
                "response_id": repair_response.response_id,
                "repair_of_response_id": response.response_id,
                "repair_reason": _safe_planner_rejection(error),
                # The repair is the execution these artifacts came from, so it is the one
                # recorded. The rejected attempt is still named by `repair_of_response_id`.
                **execution_metadata(
                    agent_type="Technical planner",
                    provider=repair_response.provider,
                    model=repair_response.model,
                    reasoning_effort=repair_response.reasoning_effort,
                    model_role=repair_response.model_role,
                    model_variable=repair_response.model_variable,
                    routing_reason=repair_response.routing_reason,
                ),
            }
            try:
                repair_payload = parse_model_json(
                    repair_response.output_text,
                    expected_keys=(
                        "architecture",
                        "integration_contract",
                        "repository_execution_plan",
                    ),
                )
                return await self._validated_artifacts(
                    feature_id=feature_id,
                    technical_prd=technical_prd,
                    repositories=repositories,
                    payload=repair_payload,
                    metadata=repair_metadata,
                    design_snapshot=design_snapshot,
                )
            except (AgentArtifactError, ValidationError) as repair_error:
                msg = "feature planner could not produce a valid plan after one repair attempt"
                # Both rejections are built from requirement, workstream, and repository
                # identifiers this module validated itself, so they are safe to persist and
                # are the only record of why planning failed once no artifact is written.
                raise AgentArtifactError(
                    msg,
                    diagnostics=[
                        f"first attempt rejected: {_safe_planner_rejection(error)}",
                        f"repair attempt rejected: {_safe_planner_rejection(repair_error)}",
                    ],
                    # Named rather than inferred: the control plane attributes a bare schema
                    # rejection from the model it rejected, and this error carries no model.
                    stage="feature_planner",
                ) from repair_error

    async def _validated_artifacts(
        self,
        *,
        feature_id: str,
        technical_prd: TechnicalPRDArtifact,
        repositories: list[RepositorySpec],
        payload: dict[str, Any],
        metadata: dict[str, Any],
        design_snapshot: DesignSnapshotArtifact | None = None,
    ) -> tuple[ArchitectureArtifact, IntegrationContractArtifact, RepositoryExecutionPlanArtifact]:
        """Create and cross-validate all planner artifacts from one model response."""
        architecture = create_artifact(
            ArchitectureArtifact,
            workflow_id=feature_id,
            artifact_id=ARTIFACT_FILENAMES["architecture"],
            producer="feature_planner",
            payload=_object(payload, "architecture"),
            metadata=metadata,
        )
        contract_payload = _object(payload, "integration_contract")
        contract_payload["feature_id"] = feature_id
        contract_payload["status"] = "approved"
        contract_payload["approved_at"] = datetime.now(UTC)
        contract = create_artifact(
            IntegrationContractArtifact,
            workflow_id=feature_id,
            artifact_id=FEATURE_ARTIFACT_FILENAMES["integration_contract"],
            producer="feature_planner",
            payload=contract_payload,
            metadata=metadata,
        )
        openapi_document = await self._contract_generator.generate_openapi(contract)
        if openapi_document is not None:
            contract = contract.model_copy(update={"openapi_document": openapi_document})
        plan_payload = _object(payload, "repository_execution_plan")
        plan_payload["feature_id"] = feature_id
        plan_payload["contract_artifact_id"] = contract.artifact_id
        dropped_dependencies = _normalize_plan_topology(plan_payload, repositories)
        dropped_task_dependencies = _normalize_task_dependencies(plan_payload)
        plan = create_artifact(
            RepositoryExecutionPlanArtifact,
            workflow_id=feature_id,
            artifact_id=FEATURE_ARTIFACT_FILENAMES["repository_execution_plan"],
            producer="feature_planner",
            payload=plan_payload,
            metadata={
                **metadata,
                "source_artifact_ids": [technical_prd.artifact_id, contract.artifact_id],
                # Recorded rather than silently discarded: a model repeatedly proposing
                # serial execution is a prompt defect worth seeing in the artifact.
                "dropped_dependency_workstream_ids": dropped_dependencies,
                # The task-level analogue, recorded for the same reason: an edge naming a task
                # that does not exist is a planning defect worth seeing in the artifact rather
                # than a reason to fail a feature.
                "dropped_task_dependencies": dropped_task_dependencies,
            },
        )
        _ensure_plan_matches_repositories(plan, repositories)
        _ensure_plan_covers_technical_requirements(plan, technical_prd)
        _ensure_plan_names_only_real_contract_sections(plan, contract)
        _ensure_plan_names_only_real_design_nodes(plan, design_snapshot)
        return architecture, contract, plan


class DeterministicFeaturePlanner:
    """Build a safe no-network plan for API mock mode and deterministic tests."""

    def __init__(self, contract_generator: ContractCodeGenerator | None = None) -> None:
        """Use a mock generator so standard tests require no frontend toolchain."""
        self._contract_generator = contract_generator or MockContractCodeGenerator()

    async def plan(
        self,
        *,
        feature_id: str,
        technical_prd: TechnicalPRDArtifact,
        repositories: list[RepositorySpec],
        reconnaissance: Sequence[RepositoryReconnaissanceArtifact] = (),
        design_snapshot: DesignSnapshotArtifact | None = None,
    ) -> tuple[ArchitectureArtifact, IntegrationContractArtifact, RepositoryExecutionPlanArtifact]:
        """Assign every repository a contract-scoped workstream deterministically.

        A cited design is assigned to every required workstream, deliberately and
        unapologetically crudely: this planner assigns by nothing but position and role, and
        the point of the mock is to exercise the *shape* -- a scoped selection reaching the
        engineer and both judges -- rather than to make a judgement it has no basis for. A
        live plan is where the assignment is actually decided.
        """
        # Accepted and unused: this planner assigns by role without reading any checkout, so
        # it has nothing to ground. Recording the IDs keeps a mock plan honest about that.
        source_metadata = {
            "source_artifact_ids": [technical_prd.artifact_id],
            "mode": "mock",
            "reconnaissance_artifact_ids": [item.artifact_id for item in reconnaissance],
            "planned_from_checkout_evidence": False,
        }
        architecture = create_artifact(
            ArchitectureArtifact,
            workflow_id=feature_id,
            artifact_id=ARTIFACT_FILENAMES["architecture"],
            producer="feature_planner",
            payload={
                "system_overview": "A parent feature workflow coordinates isolated repositories.",
                "technology_stack": {"orchestration": "LangGraph-compatible feature workflow"},
                "repository_structure": [item.name for item in repositories],
                "components": [
                    {
                        "component_id": item.repository_id,
                        "name": item.name,
                        "responsibility": f"{item.role} feature workstream",
                        "technology": "repository-defined",
                        "dependencies": [],
                    }
                    for item in repositories
                ],
                "api_contracts": [],
                "data_entities": [],
                "decisions": [
                    {
                        "decision_id": "shared-contract",
                        "title": "Use one immutable integration contract",
                        "decision": "All workstreams receive the same approved contract version.",
                        "rationale": "It prevents independent frontend/backend API drift.",
                        "consequences": ["Contract deviations require a change request."],
                    }
                ],
                "risks": [],
                "deployment_strategy": "Merge according to the recorded feature strategy.",
            },
            metadata=source_metadata,
        )
        contract = create_artifact(
            IntegrationContractArtifact,
            workflow_id=feature_id,
            artifact_id=FEATURE_ARTIFACT_FILENAMES["integration_contract"],
            producer="feature_planner",
            payload={
                "feature_id": feature_id,
                "contract_version": "1.0.0",
                "status": "approved",
                "api_style": "none",
                "endpoints": [],
                "shared_schemas": [],
                "authentication_contract": None,
                "authorization_rules": [],
                "error_contracts": [],
                "event_contracts": [],
                "environment_variables": [],
                "compatibility_policy": {
                    "policy": "Backward-compatible additive changes only.",
                    "breaking_change_allowed": False,
                    "migration_requirements": [],
                    "rollback_requirements": ["Revert both coordinated pull requests if required."],
                },
                "owning_workstreams": [
                    item.repository_id for item in repositories if item.required
                ],
                "approved_at": datetime.now(UTC),
                "openapi_document": None,
            },
            metadata=source_metadata,
        )
        workstreams = [
            _workstream_payload(item, repositories, technical_prd, design_snapshot)
            for item in repositories
        ]
        parallel_groups = _parallel_groups(workstreams)
        execution_order = [workstream_id for group in parallel_groups for workstream_id in group]
        plan = create_artifact(
            RepositoryExecutionPlanArtifact,
            workflow_id=feature_id,
            artifact_id=FEATURE_ARTIFACT_FILENAMES["repository_execution_plan"],
            producer="feature_planner",
            payload={
                "feature_id": feature_id,
                "contract_artifact_id": contract.artifact_id,
                "workstreams": workstreams,
                "execution_order": execution_order,
                "parallel_groups": parallel_groups,
                "recommended_merge_order": _recommended_merge_order(workstreams, repositories),
                "integration_test_plan": [
                    "Run repository validation and compare all workstreams to the contract."
                ],
                "merge_strategy": MergeStrategy.MANUAL,
                "deployment_strategy": DeploymentStrategy.MANUAL,
                "feature_flag_strategy": ["Use a feature flag for externally visible behavior."],
                "rollback_strategy": ["Revert coordinated pull requests in reverse merge order."],
            },
            metadata={
                **source_metadata,
                "source_artifact_ids": [technical_prd.artifact_id, contract.artifact_id],
            },
        )
        return architecture, contract, plan


def _object(payload: dict[str, Any], key: str) -> dict[str, Any]:
    """Return one model response object with an explicit boundary error on malformed output."""
    value = payload[key]
    if not isinstance(value, dict):
        msg = f"feature planner response field '{key}' must be a JSON object"
        raise AgentArtifactError(msg)
    return dict(value)


def _ensure_plan_matches_repositories(
    plan: RepositoryExecutionPlanArtifact, repositories: list[RepositorySpec]
) -> None:
    """Prevent a model response from silently dropping or inventing a workstream."""
    expected = {item.repository_id for item in repositories}
    actual = {item.repository_id for item in plan.workstreams}
    if actual != expected:
        msg = "repository execution plan must contain exactly the submitted repositories"
        raise AgentArtifactError(msg)


def _ensure_plan_names_only_real_design_nodes(
    plan: RepositoryExecutionPlanArtifact, snapshot: DesignSnapshotArtifact | None
) -> None:
    """Reject a workstream pointed at a frame the resolved design does not contain.

    The design analogue of the check below, and refused for the same reason: these strings
    reach the engineer as its instructions and the reviewer as its scope, so a frame id the
    model invented becomes an instruction to build a screen nobody drew and a criterion no
    diff can satisfy.

    The authority is `design_node_names`, shared with the selection that quotes those frames to
    the judges -- so a name this check accepts is a name they can be shown, and a name it
    rejects is one that would have reached them as an invention. Deliberately permissive about
    one case: a frame the resolution *omitted* is still a frame the design has, so assigning it
    is legitimate and the engineer is told about the omission rather than refused.

    A plan for a feature with no design cannot name a frame at all, and a workstream that names
    none is the ordinary case; both pass without the snapshot being consulted.
    """
    named = {
        workstream.workstream_id: sorted(set(workstream.design_nodes))
        for workstream in plan.workstreams
        if workstream.design_nodes
    }
    if not named:
        return
    known = frozenset() if snapshot is None else design_node_names(snapshot)
    unknown = {
        workstream_id: [item for item in nodes if item not in known]
        for workstream_id, nodes in named.items()
    }
    unknown = {key: value for key, value in unknown.items() if value}
    if not unknown:
        return
    detail = "; ".join(
        f"workstream '{workstream_id}' names {nodes}"
        for workstream_id, nodes in sorted(unknown.items())
    )
    available = sorted(known)
    msg = (
        "every design frame a workstream is assigned must exist in this feature's resolved "
        f"design snapshot, and these do not: {detail}. The snapshot contains "
        f"{available or 'no frames at all'}."
    )
    raise AgentArtifactError(msg, stage="feature_planner")


def _ensure_plan_names_only_real_contract_sections(
    plan: RepositoryExecutionPlanArtifact, contract: IntegrationContractArtifact
) -> None:
    """Reject a workstream that points at a contract section the contract does not contain.

    These two fields were the one part of the plan nothing checked. They are typed as bare
    strings, and they do not stay in the artifact: the runtime puts them verbatim into the
    engineer's task -- "Implement sections: X. Consume sections: Y." -- and into the scope the
    reviewer judges against. So an operation ID the model invented while writing the contract
    and the plan in the same response became an instruction to build an endpoint that is not
    in the contract, and a criterion no diff could satisfy.

    Deterministic, and therefore repaired rather than shipped: the planner's bounded repair
    path already exists for exactly this class of defect, and it is told which names were
    wrong and what the real ones are.

    The set of real names comes from `contract_section_names`, shared with the selection that
    quotes those sections to the judges. A name this check accepts is therefore a name the
    judges can be shown, and a name it rejects is one that would be reported as absent to them:
    the two cannot answer "does the contract define this" differently.
    """
    known = contract_section_names(contract)
    unknown: dict[str, list[str]] = {}
    for workstream in plan.workstreams:
        named = [
            *workstream.contract_sections_implemented,
            *workstream.contract_sections_consumed,
        ]
        missing = sorted({item for item in named if item not in known})
        if missing:
            unknown[workstream.workstream_id] = missing
    if not unknown:
        return
    detail = "; ".join(
        f"workstream '{workstream_id}' names {sections}"
        for workstream_id, sections in sorted(unknown.items())
    )
    available = sorted(known)
    msg = (
        "every contract section a workstream implements or consumes must exist in the "
        f"integration contract, and these do not: {detail}. The contract defines "
        f"{available or 'no sections at all'}."
    )
    raise AgentArtifactError(msg, stage="feature_planner")


def _ensure_plan_covers_technical_requirements(
    plan: RepositoryExecutionPlanArtifact, technical_prd: TechnicalPRDArtifact
) -> None:
    """Reject plans that lose or invent requirement ownership before child fan-out."""
    known_requirement_ids = {
        requirement.requirement_id
        for requirement in [
            *technical_prd.functional_requirements,
            *technical_prd.non_functional_requirements,
        ]
    }
    acceptance_ids_by_requirement = {
        requirement.requirement_id: {
            f"{requirement.requirement_id}:ac-{index}"
            for index, _criterion in enumerate(requirement.acceptance_criteria, start=1)
        }
        for requirement in [
            *technical_prd.functional_requirements,
            *technical_prd.non_functional_requirements,
        ]
    }
    assigned_requirement_ids: set[str] = set()
    has_scoped_references = any(
        workstream.scoped_requirements or workstream.shared_requirements
        for workstream in plan.workstreams
    )
    for workstream in plan.workstreams:
        references = [*workstream.scoped_requirements, *workstream.shared_requirements]
        referenced_ids = {item.requirement_id for item in references}
        # Legacy persisted plans have only requirement_ids.  They remain readable but
        # fresh planner output must use explicit scoped references.
        candidate_ids = referenced_ids if has_scoped_references else set(workstream.requirement_ids)
        unknown_requirement_ids = candidate_ids - known_requirement_ids
        if unknown_requirement_ids:
            # The valid identifiers are named, not just the invalid ones. Told only that a
            # value was unknown, a repair moved it from scoped to out-of-scope instead of
            # removing it, because nothing in the message said what a requirement id is.
            msg = (
                f"workstream '{workstream.workstream_id}' assigns unknown technical requirements: "
                f"{sorted(unknown_requirement_ids)}. Remove them; they are not requirement ids. "
                f"The only valid requirement ids are: {sorted(known_requirement_ids)}"
            )
            raise AgentArtifactError(msg)
        for reference in references:
            unknown_acceptance_ids = set(
                reference.acceptance_criterion_ids
            ) - acceptance_ids_by_requirement.get(reference.requirement_id, set())
            if unknown_acceptance_ids:
                msg = (
                    f"workstream '{workstream.workstream_id}' references unknown acceptance "
                    f"criteria: {sorted(unknown_acceptance_ids)}"
                )
                raise AgentArtifactError(msg)
        unknown_out_of_scope_ids = set(workstream.out_of_scope_requirements) - known_requirement_ids
        if unknown_out_of_scope_ids:
            msg = (
                f"workstream '{workstream.workstream_id}' marks unknown requirements out of scope: "
                f"{sorted(unknown_out_of_scope_ids)}. Remove them rather than relocating them. "
                f"The only valid requirement ids are: {sorted(known_requirement_ids)}"
            )
            raise AgentArtifactError(msg)
        if workstream.required:
            assigned_requirement_ids.update(candidate_ids)
    unassigned_requirement_ids = known_requirement_ids - assigned_requirement_ids
    if unassigned_requirement_ids:
        msg = (
            "repository execution plan must assign every technical requirement to at least "
            f"one required workstream: {sorted(unassigned_requirement_ids)}"
        )
        raise AgentArtifactError(msg)


def _mock_design_nodes(
    repository: RepositorySpec, snapshot: DesignSnapshotArtifact | None
) -> list[str]:
    """Assign a mock workstream the frames whose citation names its repository, or all of them.

    Only the frames that actually resolved: assigning one the snapshot merely *mentions* would
    make the mock plan fail the planner's own validation, which accepts an omitted frame but
    not one that is absent or unreachable.
    """
    if snapshot is None:
        return []
    return [
        item.node_id
        for item in snapshot.nodes
        if not item.applies_to or repository.repository_id in item.applies_to
    ]


def _workstream_payload(
    repository: RepositorySpec,
    repositories: list[RepositorySpec],
    technical_prd: TechnicalPRDArtifact,
    design_snapshot: DesignSnapshotArtifact | None = None,
) -> dict[str, Any]:
    """Build a portable mock assignment without guessing implementation files."""
    earlier = _build_artifact_dependencies(repository, repositories)
    all_requirements = [
        *technical_prd.functional_requirements,
        *technical_prd.non_functional_requirements,
    ]
    required_repositories = [item for item in repositories if item.required]
    implementation_owner = (
        required_repositories[0].repository_id
        if required_repositories
        else repository.repository_id
    )
    scoped = [
        {
            "requirement_id": requirement.requirement_id,
            "acceptance_criterion_ids": [
                f"{requirement.requirement_id}:ac-{index}"
                for index, _criterion in enumerate(requirement.acceptance_criteria, start=1)
            ],
            "responsibility": "implements"
            if repository.repository_id == implementation_owner
            else "consumes",
        }
        for requirement in all_requirements
    ]
    return {
        "workstream_id": repository.repository_id,
        "repository_id": repository.repository_id,
        "role": repository.role,
        "requirement_ids": [requirement.requirement_id for requirement in all_requirements],
        "scoped_requirements": scoped,
        "out_of_scope_requirements": [],
        "shared_requirements": [],
        "responsibilities": [f"Implement {repository.name}'s assigned feature work."],
        "task_ids": [f"{repository.repository_id}-implementation"],
        # One task per mock workstream, so there is nothing for it to wait for. The mock
        # exercises the shape, and the shape of no ordering is the empty list.
        "task_dependencies": [],
        "dependency_workstream_ids": earlier,
        "contract_sections_consumed": [],
        "contract_sections_implemented": [],
        # Every frame the design resolved, to whichever repositories the citation scoped it to
        # -- or to all of them when it scoped none, because a mock planner has no basis for
        # choosing and guessing from `role` is exactly what this platform must not do.
        "design_nodes": _mock_design_nodes(repository, design_snapshot),
        "acceptance_criteria": ["Repository review is approved against the shared contract."],
        "test_requirements": ["Run the repository's configured validation commands."],
        "documentation_requirements": ["Document the feature integration behavior."],
        "expected_files_or_areas": [],
        "implementation_expectations": [
            {
                "requirement_id": requirement.requirement_id,
                # The plan is created before any submitted repository is checked out.
                # Keep its completion contract language- and layout-neutral; the live
                # child records concrete checkout evidence before it invokes coding.
                "expected_change_categories": ["production", "test"],
                "expected_source_areas": [],
                "tests_required": True,
            }
            for requirement in all_requirements
        ],
        "required": repository.required,
    }


def _build_artifact_dependencies(
    repository: RepositorySpec, repositories: list[RepositorySpec]
) -> list[str]:
    """Return only the repositories this one must physically wait for.

    The integration contract is approved and immutable before any child starts, so a
    repository that merely consumes it can be implemented in parallel with the one that
    serves it. Only a produced build artifact -- a shared library that siblings compile
    or link against -- is a real execution barrier. Treating anything else as a
    dependency lets one failing repository starve unrelated work.
    """
    if repository.role in _BUILD_ARTIFACT_ROLES:
        return []
    return [
        item.repository_id
        for item in repositories
        if item.repository_id != repository.repository_id
        and item.role in _BUILD_ARTIFACT_ROLES
        and item.required
    ]


def _parallel_groups(workstreams: list[dict[str, Any]]) -> list[list[str]]:
    """Layer the dependency graph so every independent workstream fans out together."""
    dependencies = {
        str(item["workstream_id"]): {str(value) for value in item["dependency_workstream_ids"]}
        for item in workstreams
    }
    declared = [str(item["workstream_id"]) for item in workstreams]
    groups: list[list[str]] = []
    scheduled: set[str] = set()
    while len(scheduled) < len(declared):
        layer = [
            workstream_id
            for workstream_id in declared
            if workstream_id not in scheduled and dependencies[workstream_id] <= scheduled
        ]
        if not layer:
            msg = "repository execution plan contains a workstream dependency cycle"
            raise AgentArtifactError(msg)
        groups.append(layer)
        scheduled.update(layer)
    return groups


def _recommended_merge_order(
    workstreams: list[dict[str, Any]], repositories: list[RepositorySpec]
) -> list[str]:
    """Keep explicit operator sequencing as merge guidance instead of discarding it."""
    if all(item.implementation_order is None for item in repositories):
        return []
    rank = {
        item.repository_id: (item.implementation_order is None, item.implementation_order or 0)
        for item in repositories
    }
    ordered = sorted(
        workstreams,
        key=lambda item: rank.get(str(item["repository_id"]), (True, 0)),
    )
    return [str(item["workstream_id"]) for item in ordered]


def _normalize_plan_topology(
    plan_payload: dict[str, Any], repositories: list[RepositorySpec]
) -> dict[str, list[str]]:
    """Stop a planner model from choosing how repositories are scheduled.

    The model owns requirement ownership and contract design; it does not own execution
    topology. Any dependency it declares that is not a build-artifact dependency is
    dropped and reported, then groups are rebuilt from the surviving graph.
    """
    workstreams = plan_payload.get("workstreams")
    if not isinstance(workstreams, list) or not workstreams:
        return {}
    entries = [item for item in workstreams if isinstance(item, dict)]
    if len(entries) != len(workstreams):
        return {}
    roles = {item.repository_id: item.role for item in repositories}
    producers = {
        str(entry.get("workstream_id"))
        for entry in entries
        if roles.get(str(entry.get("repository_id"))) in _BUILD_ARTIFACT_ROLES
    }
    dropped: dict[str, list[str]] = {}
    for entry in entries:
        declared = entry.get("dependency_workstream_ids")
        if not isinstance(declared, list):
            continue
        workstream_id = str(entry.get("workstream_id"))
        kept = [
            str(item) for item in declared if str(item) in producers and str(item) != workstream_id
        ]
        removed = [str(item) for item in declared if str(item) not in kept]
        if removed:
            dropped[workstream_id] = removed
        entry["dependency_workstream_ids"] = kept
    groups = _parallel_groups(entries)
    plan_payload["parallel_groups"] = groups
    plan_payload["execution_order"] = [item for group in groups for item in group]
    plan_payload["recommended_merge_order"] = _recommended_merge_order(entries, repositories)
    return dropped


def _normalize_task_dependencies(plan_payload: dict[str, Any]) -> dict[str, dict[str, list[str]]]:
    """Remove the task edges no order can satisfy, and report them per workstream.

    The treatment `_normalize_plan_topology` gives the repository graph, for the same reason.
    An edge pointing at a task the workstream never declared, a task waiting on itself, or a
    set of tasks waiting on each other is dropped here, which leaves the workstream saying what
    it would have said without the mistake -- these tasks are independent -- rather than failing
    a feature over a field nothing is scheduled from yet. A malformed *shape* is left alone for
    schema validation and the bounded repair path that already exists for it.
    """
    workstreams = plan_payload.get("workstreams")
    if not isinstance(workstreams, list):
        return {}
    dropped: dict[str, dict[str, list[str]]] = {}
    for entry in workstreams:
        if not isinstance(entry, dict):
            continue
        declared = entry.get("task_dependencies")
        task_ids = entry.get("task_ids")
        if not isinstance(declared, list) or not declared:
            continue
        if not isinstance(task_ids, list) or not all(isinstance(item, str) for item in task_ids):
            continue
        if not all(isinstance(item, dict) for item in declared):
            continue
        known = [str(item) for item in task_ids]
        requested: dict[str, list[str]] = {}
        removed: dict[str, list[str]] = {}
        malformed = False
        for item in declared:
            task_id = item.get("task_id")
            depends_on = item.get("depends_on", [])
            if not isinstance(task_id, str) or not isinstance(depends_on, list):
                malformed = True
                break
            values = [value for value in depends_on if isinstance(value, str)]
            if task_id in known:
                requested[task_id] = values
            elif values:
                removed[task_id] = sorted(set(values))
        if malformed:
            continue
        _order, unresolvable = ordered_task_ids(known, requested)
        for task_id, values in unresolvable.items():
            removed[task_id] = sorted({*removed.get(task_id, []), *values})
        entry["task_dependencies"] = [
            {
                "task_id": task_id,
                "depends_on": [
                    value for value in values if value not in set(removed.get(task_id, ()))
                ],
            }
            for task_id, values in requested.items()
        ]
        if removed:
            dropped[str(entry.get("workstream_id"))] = removed
    return dropped


__all__ = ["DeterministicFeaturePlanner", "FeaturePlanner", "FeaturePlannerAgent"]
